### ISSUE TITLE
Editing Art

### ISSUE THREAD

**Issue by AshwiniTembhurne** [Damitwhy/Hidden-Brush#10]
As a user,
I want to be able to edit the details of my uploaded artwork, So that I can update the information or correct any mistakes.

Acceptance Criteria:

- [ ] Users can access an "Edit" option for any artwork they have uploaded.
- [ ] Users can change the title, description, and tags associated with their artwork.
- [ ] Users can replace the existing image with a new one if needed.
- [ ] Changes are saved and reflected in the gallery immediately after submission.

**Comment by Damitwhy** [comment]
completed
