### ISSUE TITLE
Deleting Art

### ISSUE THREAD

**Issue by AshwiniTembhurne** [Damitwhy/Hidden-Brush#11]
As a user,
I want to be able to delete my artwork from the gallery, So that I can remove content that I no longer wish to share.

Acceptance Criteria:

- [ ] Users can access a "Delete" option for any artwork they have uploaded.
- [ ] The app prompts the user to confirm the deletion before proceeding.
- [ ] Once confirmed, the artwork is permanently removed from the gallery.

**Comment by Damitwhy** [comment]
Delete html, view and url is in place just need to add buttons to image_detail and gallery when authenticated user is == image owner

**Comment by Damitwhy** [comment]
completed
