### ISSUE TITLE
 User Registration 

### ISSUE THREAD

**Issue by AshwiniTembhurne** [Damitwhy/Hidden-Brush#26]
As a new user, I want to register for an account on the Hidden Brush platform so that I can access exclusive features like liking artwork, commenting on pieces, and saving my favorite artworks.

Acceptance Criteria:

- The registration form should include fields for a username, email address, password, and password confirmation, with all fields being required.
- The form should validate that the username is unique, the email is in a valid format, and the password meets security criteria and matches the confirmation field.
- Upon successful registration, the system should create a new user account, securely store the hashed password, and automatically log the user in, redirecting them to the gallery page.
- If there are validation errors, appropriate error messages should be displayed, and the user should not lose their input data.
- The system should provide feedback after registration, welcoming the user and guiding them on the next steps.

**Comment by Damitwhy** [comment]
completed
